### ISSUE TITLE
I guess there is wrong assignment

### ISSUE THREAD

**Issue by salda** [EricOuellet2/ConvexHull#1]
https://github.com/EricOuellet2/ConvexHull/blob/c2b5944daefd21cdc3f0c58e1b73e81ee7730df6/OuelletConvexHullCpp/OuelletHull.cpp#L147

IMHO, it should be "q2p2 = pt;" instead of "q2p2.y = pt.y;"

I refactored the whole code, so it takes only about 160 lines in the end, but this is IMHO a bug.

**Comment by EricOuellet2** [comment]
WOW! WOW! WOW! You are totally right! Thank you so much to letting me know! I Just corrected it.
I think it had the bad side effect of modifying the original source points which is really bad. Great find!
...I'm curious about your refactoring. Do you have same performance?

**Comment by EricOuellet2** [comment]
Also... although it should work well in most cases. There is a potential problem if the convex hull (in CPP) results become too big (~100 000 points). The AVL version solve this issue. I did not convert my C# AVL code to CPP because i'm missing time. But I think you could achieve similar performance as the implementation with an array (has to be proven). It is a real fun to debug (version with AVL) :-) !!!
Just for my curiosity, who are you? Do you have any profile somewhere that I could take a look?

**Comment by EricOuellet2** [comment]
Fixed

**Comment by salda** [comment]
Who am I => I am a programmer that received an Assignment as a part of hiring process to compute the convex hull. 
And I somehow managed that the best way, how to do it, is your method, but I didn't know, how to implement it. Then I found out it was already written by you few days before that, so I used it. 
I removed the duplicate code and code not needed for me from the C/C++ implementation and I used containers instead of C-style arrays so in the end I use your implementation for the most complicated part of that assignment. (I could use some older and slower method, but I liked the fact that you just implemented it few days before I started doing that task)
My LI account is https://www.linkedin.com/in/lukas-salich-0451005a/

**Comment by EricOuellet2** [comment]
Hi Lukas,

Nice to know that you used my code.
It is nice to use a standard container in order to  make it easier to maintain and understand but…
I just want to an information: The current implementation using a vector (an array) is working perfectly when the amount of convex hull points stay around less than 100 000 which should always be true in most, if not all normal usage. But, if you want something closer to perfection, more stable in all cases, you should use a balanced tree like an AVL or Red-Black tree. I prefer an AVL for that case. But it is not a must, I did in C# but not in C++ (too much work for me – too much time).

Just for curiosity, why did you change the container if the algorithm was working fine as is? Using another container should make it a little bit slower.

Thanks to let me know about it.
Good luck!
Bye,
Eric Ouellet

**Comment by salda** [comment]
Hi Eric and you are right, but I also don't have the time for changing the underlying storage. I used vector, because I had vector on input and also it was more readable that way for me than using arrays and pointers. 

I can make it faster in the future, but I have a lot of work now. For my assignment, it was good enough. 
I don't even have time to test the speed of my code (I ported it outside Visual Studio solution).
